version: '2'
services:
  nginx:
    image: nginx:latest
    restart: 'no'
    volumes:
      - ./devops:/etc/nginx/conf.d
    links:
      - app
    depends_on:
      - app
    ports:
      - 80:80

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fenix
      MYSQL_USER: fenix
      MYSQL_PASSWORD: p@55w0rd
    ports:
      - 3306
    logging:
      driver: "none"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: uwsgi --http :3000 --chdir . --module fenix.wsgi 
#python manage.py runserver 0.0.0.0:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    ports:
      - 8080:3000
    links:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A fenix worker -l info
    volumes:
      - ./:/usr/src/app
    links:
      - rabbitmq:rabbitmq
